apiVersion: rbac.authorization.k8s.io/v
kind: RoleBinding
metadata:
  name: devuser-developer-binding
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  - kind: Role
    name: developer
    apiGroup: rbac.uthorization.k8s.io
#-->kubectl create -f devuser-developer-binding.yaml