apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
     app: myapp
     country: IN
spec:
  containers: 
    - name: myapp1
      image: httpd
    - name: backend-container
      image: nginx

#command=
#1.kubectl get pods
#2.delete pods= kubectl delete deployment nginx
#3. kubectl create -f pod-defination.yml