apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
   
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        country: IN
    spec:
      containers: 
        - name: mginx-container
          image: httpd
  replicas: 3
  # replicas: 3
  # selector:
  #   dc: IN
  # template:
  #   metadata:
  #     name: app1
  #     labels:
  #       dc: IN
  #   spec:
  #     containers:
  #     - name: myapp1
  #       image: httpd


#kubectl create -f replicationController.yml
#kubectl get rc
#kubectl get rc <name> 



