apiVersion: vl
kind: Pod
metadata:
  name: simple-webapp-color
labels:
  name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
      - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: 250m
      Limits: 
        memory: "128Mi"
        cpu: 500m